GET http://localhost:5000/users

###
GET http://localhost:5000/users/ca28bbb9-6d91-4c9a-95dc-2d894e85a564

###
GET http://localhost:5000/me

###
DELETE  http://localhost:5000/logout



###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeokingyang@yahoo.com",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeokingyang@yahoo.com",
    "password": ""
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yennykwok@yahoo.com",
    "password": "123456"
}


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Yeo King",
    "email": "yeeokingyang@yahoo.com",
    "password": "123456",
    "confPassword": "123456",
    "role":"admin"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Yenny",
    "email": "yennykwok@yahoo.com",
    "password": "123456",
    "confPassword": "123456",
    "role":"staff"
}

###
PATCH http://localhost:5000/users/ca28bbb9-6d91-4c9a-95dc-2d894e85a564
Content-Type: application/json

{
    "name": "Yeo King",
    "email": "yeokingyang@yahoo.com",
    "password": "",
    "confPassword": "",
    "role":"admin"
}

###
DELETE  http://localhost:5000/users/ee6c7357-aead-4238-9799-a6475cfd54b4


###
POST http://localhost:5000/items
Content-Type: application/json

{
    "uuid": "CH100",
    "name": "Clamp Hose",
    "debit": "4000",
    "credit": "7000"
}

###
GET http://localhost:5000/items/

###
GET http://localhost:5000/items/CH100