GET http://localhost:5000/users

###
GET http://localhost:5000/users/ca28bbb9-6d91-4c9a-95dc-2d894e85a564


###
GET http://localhost:5000/me

###
DELETE  http://localhost:5000/logout

###
GET http://localhost:5000/users?search_query=yeo&page=0&limit=10

###
GET http://localhost:5000/users?page=0&limit=10


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeokingyang@yahoo.com",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeokingyang@yahoo.com",
    "password": ""
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yennykwok@yahoo.com",
    "password": "123456"
}


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Yeo King",
    "email": "yeeokingyang@yahoo.com",
    "password": "123456",
    "confPassword": "123456",
    "role":"admin"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "saul",
    "email": "saul@yahoo.com",
    "password": "123456",
    "confPassword": "123456",
    "role":"staff"
}


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Yenny",
    "email": "yennykwok@yahoo.com",
    "password": "123456",
    "confPassword": "123456",
    "role":"staff"
}

###
PATCH http://localhost:5000/users/ca28bbb9-6d91-4c9a-95dc-2d894e85a564
Content-Type: application/json

{
    "name": "Yeo King",
    "email": "yeokingyang@yahoo.com",
    "password": "",
    "confPassword": "",
    "role":"admin"
}

###
DELETE  http://localhost:5000/users/ee6c7357-aead-4238-9799-a6475cfd54b4


###
POST http://localhost:5000/items
Content-Type: application/json

{
    "iuid": "CH2",
    "name": "Clamp Hose 2 inch",
    "credit": "7500",
    "type": "Rujika",
    "quantification": "Piece",
    "explanation": "nothing"
}

###
PATCH  http://localhost:5000/items/CH1000
Content-Type: application/json

{
    "iuid": "CH100",
    "name": "Clamp Hose",
    "debit": "0",
    "credit": "7500"
}

###
DELETE   http://localhost:5000/items/AMPB-100cc-VC

###
GET http://localhost:5000/items/

###
GET http://localhost:5000/items/CH-1

###
GET http://localhost:5000/items?search_query=Clam&page=0&limit=10

###
GET http://localhost:5000/outgoingItems?search_query=cl&page=0&limit=10

###
GET http://localhost:5000/outgoingItems/11

###
GET http://localhost:5000/outgoingItems/sumTotalCredit

###
POST http://localhost:5000/outgoingItems
Content-Type: application/json

{
  "iuid": "CH1000",
  "quantitySold": 2
}

###
PATCH  http://localhost:5000/outgoingItems/2
Content-Type: application/json

{

    "credit": "3000",
    "quantitySold": "3"
}

###
DELETE  http://localhost:5000/outgoingItems/10


###
GET http://localhost:5000/incomingItems

###
GET http://localhost:5000/incomingItems?search_query=cl&page=0&limit=10

###
GET http://localhost:5000/incomingItems/1


###
POST http://localhost:5000/incomingItems
Content-Type: application/json

{
  "iuid": "CH1",
  "debit": "2500",
  "quantityPurchased": 2
}

###
PATCH  http://localhost:5000/incomingItems/1
Content-Type: application/json

{

    "debit": "3000",
    "quantityPurchased": "3"
}

###
DELETE  http://localhost:5000/incomingItems/1



###
GET http://localhost:5000/wishlistitems


###
GET http://localhost:5000/staffs/count


###
GET http://localhost:5000/inventory/stat

###
GET http://localhost:5000/expense

###
GET http://localhost:5000/income

###
GET http://localhost:5000/expenseThisMonth

###
GET http://localhost:5000/incomeThisMonth

###
GET http://localhost:5000/incomeDifferences

###
GET http://localhost:5000/incomePrevious

###
GET http://localhost:5000/report/incomebyDaily?year=2023&month=1


###
GET http://localhost:5000/incomeForecast
